
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: admin
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: meetup_development

test:
  <<: *default
  database: meetup_test


production:
  <<: *default
  database: meetup_production
  username: meetup
  password: <%= ENV['MEETUP_DATABASE_PASSWORD'] %>
